<?php

namespace AppBundle\Repository;

/**
 * Castle Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CastleRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     *
     * @return array
     *
     */
    public function getCastlelist(){

        $return = $this->getEntityManager()
            ->createQuery(
                'SELECT castle, clan FROM AppBundle:Castle castle LEFT JOIN castle.clanId clan');

        return $return->getResult();

    }


}
