<?php

namespace AppBundle\Repository;

/**
 * ClanData Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClanDataRepository extends \Doctrine\ORM\EntityRepository
{

}
