<?php

namespace AppBundle\Repository;

/**
 * ClanHall Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClanHallRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     *
     * @return array
     *
     */
    public function getChlist(){

        $return = $this->getEntityManager()
            ->createQuery(
                'SELECT ch, clan FROM AppBundle:ClanHall ch LEFT JOIN ch.clanId clan');

        return $return->getResult();

    }


}
