<?php

namespace AppBundle\Repository;

/**
 * Raidboss_spawnlist Repository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Raidboss_spawnlistRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     *
     * @return array
     *
     */
    public function getRBlist(){

        $return = $this->getEntityManager()
            ->createQuery(
                'SELECT rb, npc FROM AppBundle:Raidboss_spawnlist rb JOIN rb.npc npc');

        return $return->getResult();

    }
}
