imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    app.locales: en|ru
    locale_supported: ['en','ru']

framework:
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true
    default_locale: '%locale%'
    translator: { fallbacks: [en] }

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    globals:
        forum_url: '%forum_url%'

# Doctrine Configuration
doctrine:
    dbal:
        default_connection: login
        connections:
            login:
                driver:   pdo_mysql
                host:     '%database_host_login%'
                port:     '%database_port_login%'
                dbname:   '%database_name_login%'
                user:     '%database_user_login%'
                password: '%database_password_login%'
                charset:  UTF8
            game:
                driver:   pdo_mysql
                host:     '%database_host_game%'
                port:     '%database_port_game%'
                dbname:   '%database_name_game%'
                user:     '%database_user_game%'
                password: '%database_password_game%'
                charset:  UTF8
            web:
                driver:   pdo_mysql
                host:     '%database_host_web%'
                port:     '%database_port_web%'
                dbname:   '%database_name_web%'
                user:     '%database_user_web%'
                password: '%database_password_web%'
                charset:  UTF8
    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        default_entity_manager: login
        entity_managers:
            login:
                connection: login
                mappings:
                    AppBundle:  ~
            game:
                connection: game
                mappings:
                    AppBundle: ~
            web:
                connection: web
                mappings:
                    AppBundle: ~


# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    encryption: ssl
    port: 465
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }


#my own configs

#
#fos_rest:
#    param_fetcher_listener: true
#    body_listener: true
#    format_listener:
#        enabled: true
#        rules:
##            - { path: '^/user/api', priorities: ['json'], fallback_format: 'html' }
#    versioning: true
#    view:
#        view_response_listener: 'force'
