# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: ~

        user_provider:
             entity:
                 class: AppBundle:User
                 property: username

    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
        - { path: ^/user, roles: [ROLE_USER, ROLE_ADMIN] }


    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
         dev:
              pattern: ^/(_(profiler|wdt)|css|images|js)/
              security: false

         user_secured_area:
              pattern:   ^/
              anonymous: ~
              provider: user_provider
              form_login:
                  login_path: /login
                  check_path: /login
                  default_target_path: /
              logout:
                   path:  /logout
                   target: /

