# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory: ~

        user_provider:
             entity:
                 class: AppBundle:User
                 property: username

    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt

    access_control:
        - { path: ^/(en|ru)/user, roles: [ROLE_USER] }


    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
         dev:
              pattern: ^/(_(profiler|wdt)|css|images|js)/
              security: false

         user_secured_area:
              pattern:   ^/
              anonymous: ~
              provider: user_provider
              form_login_captcha:
                  login_path: /en/login
                  check_path: /en/login
                  username_parameter: "login_form[username]"
                  password_parameter: "login_form[password]"
                  csrf_parameter: "login_form[_token]"
                  default_target_path: homepage
                  google_recaptcha_secret: 6LfmakQUAAAAAI6OjWw_QmwuUOHzVQ5xq4FoSb-L
              logout:
                   path:  /logout
                   target: /

